name: Verification de distribution.json

on:
  push:
    branches-ignore: [master]
jobs:
  build:
    name: Vérifier le validité du fichier
    runs-on: ubuntu-latest
    steps:
      - name: Copier le code
        uses: actions/checkout@v2
      - name: Utiliser JSONLint sur le code
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSON: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
